interface CosmeticProduct {
  id: number;
  name: string;
  price: number;
  category: string;
  image: string;
}

const cosmeticProducts: CosmeticProduct[] = [
  {
    id: 1,
    name: "Hydrating Face Serum",
    price: 599,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/skincare,serum?lock=1",
  },
  {
    id: 2,
    name: "Daily Face Moisturizer",
    price: 449,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/skincare,moisturizer?lock=2",
  },
  {
    id: 3,
    name: "Vitamin C Face Serum",
    price: 699,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/skincare,serum?lock=3",
  },
  {
    id: 4,
    name: "Gentle Face Cleanser",
    price: 349,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/skincare,cleanser?lock=4",
  },
  {
    id: 5,
    name: "Aloe Vera Gel",
    price: 299,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/aloe,skincare?lock=5",
  },
  {
    id: 6,
    name: "Rose Water Toner",
    price: 249,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/toner,skincare?lock=6",
  },
  {
    id: 7,
    name: "Hydrating Sheet Mask",
    price: 199,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/facemask,skincare?lock=7",
  },
  {
    id: 8,
    name: "Night Repair Cream",
    price: 749,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/facecream,skincare?lock=8",
  },
  {
    id: 9,
    name: "Under Eye Cream",
    price: 499,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/eyecare,cream?lock=9",
  },
  {
    id: 10,
    name: "Clay Face Mask",
    price: 399,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/clay,facemask?lock=10",
  },

  {
    id: 11,
    name: "Matte Lipstick",
    price: 499,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/lipstick,makeup?lock=11",
  },
  {
    id: 12,
    name: "Nude Lipstick",
    price: 449,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/lipstick,nude?lock=12",
  },
  {
    id: 13,
    name: "Liquid Foundation",
    price: 799,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/foundation,makeup?lock=13",
  },
  {
    id: 14,
    name: "Compact Powder",
    price: 399,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/compact,powder?lock=14",
  },
  {
    id: 15,
    name: "Blush Palette",
    price: 549,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/blush,makeup?lock=15",
  },
  {
    id: 16,
    name: "Eyeshadow Palette",
    price: 699,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/eyeshadow,makeup?lock=16",
  },
  {
    id: 17,
    name: "Waterproof Mascara",
    price: 399,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/mascara,makeup?lock=17",
  },
  {
    id: 18,
    name: "Liquid Eyeliner",
    price: 299,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/eyeliner,makeup?lock=18",
  },
  {
    id: 19,
    name: "Lip Gloss",
    price: 349,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/lipgloss,makeup?lock=19",
  },
  {
    id: 20,
    name: "Makeup Brush Set",
    price: 599,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/makeup,brushes?lock=20",
  },

  {
    id: 21,
    name: "Shampoo",
    price: 399,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/shampoo,haircare?lock=21",
  },
  {
    id: 22,
    name: "Anti-Frizz Hair Serum",
    price: 499,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/hair,serum?lock=22",
  },
  {
    id: 23,
    name: "Hair Conditioner",
    price: 399,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/hair,conditioner?lock=23",
  },
  {
    id: 24,
    name: "Hair Mask",
    price: 549,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/hair,mask?lock=24",
  },
  {
    id: 25,
    name: "Hair Oil",
    price: 299,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/hair,oil?lock=25",
  },
  {
    id: 26,
    name: "Curl Defining Cream",
    price: 599,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/curly,hair?lock=26",
  },
  {
    id: 27,
    name: "Heat Protection Spray",
    price: 449,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/hair,spray?lock=27",
  },
  {
    id: 28,
    name: "Hair Styling Gel",
    price: 299,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/hair,gel?lock=28",
  },
  {
    id: 29,
    name: "Scalp Care Serum",
    price: 649,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/scalp,hair?lock=29",
  },
  {
    id: 30,
    name: "Dry Shampoo",
    price: 499,
    category: "Hair Care",
    image: "https://loremflickr.com/600/600/dryshampoo,hair?lock=30",
  },

  {
    id: 31,
    name: "Body Lotion",
    price: 349,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/body,lotion?lock=31",
  },
  {
    id: 32,
    name: "Body Scrub",
    price: 399,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/body,scrub?lock=32",
  },
  {
    id: 33,
    name: "Body Wash",
    price: 349,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/bodywash?lock=33",
  },
  {
    id: 34,
    name: "Hand Cream",
    price: 249,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/handcream?lock=34",
  },
  {
    id: 35,
    name: "Foot Cream",
    price: 299,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/footcream?lock=35",
  },
  {
    id: 36,
    name: "Bath Salt",
    price: 449,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/bath,salt?lock=36",
  },
  {
    id: 37,
    name: "Body Butter",
    price: 499,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/body,butter?lock=37",
  },
  {
    id: 38,
    name: "Body Mist",
    price: 399,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/body,mist?lock=38",
  },
  {
    id: 39,
    name: "Hand Wash",
    price: 249,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/handwash?lock=39",
  },
  {
    id: 40,
    name: "Body Oil",
    price: 549,
    category: "Body Care",
    image: "https://loremflickr.com/600/600/body,oil?lock=40",
  },

  {
    id: 41,
    name: "Cleansing Balm",
    price: 649,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/cleansing,balm?lock=41",
  },
  {
    id: 42,
    name: "Sunscreen SPF 50",
    price: 599,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/sunscreen?lock=42",
  },
  {
    id: 43,
    name: "Lip Balm",
    price: 199,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/lipbalm?lock=43",
  },
  {
    id: 44,
    name: "Pore Minimizing Serum",
    price: 699,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/serum,skincare?lock=44",
  },
  {
    id: 45,
    name: "Niacinamide Serum",
    price: 599,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/niacinamide,serum?lock=45",
  },
  {
    id: 46,
    name: "Micellar Water",
    price: 349,
    category: "Skincare",
    image: "https://loremflickr.com/600/600/micellar,water?lock=46",
  },
  {
    id: 47,
    name: "Makeup Remover",
    price: 399,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/makeup,remover?lock=47",
  },
  {
    id: 48,
    name: "Highlighter Palette",
    price: 599,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/highlighter,makeup?lock=48",
  },
  {
    id: 49,
    name: "Lip Liner",
    price: 249,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/lipliner,makeup?lock=49",
  },
  {
    id: 50,
    name: "Beauty Blender Set",
    price: 299,
    category: "Makeup",
    image: "https://loremflickr.com/600/600/makeup,sponge?lock=50",
  },
];

export default cosmeticProducts;